MACHINE=
SCRIPT_NAME=elfm9s12xg
OUTPUT_FORMAT="elf32-m68hc12"
TEXT_MEMORY=text
DATA_MEMORY=data
EEPROM_MEMORY=eeprom
ARCH=m9s12xg
MAXPAGESIZE=32
GENERIC_BOARD=yes
TEMPLATE_NAME=elf32
EXTRA_EM_FILE=m9s12xgelf

